# Generated by Django 3.0.3 on 2020-05-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbUsersModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='birthday',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='submission_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_class',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_gender',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_grade',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_pass',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_roleID',
            field=models.IntegerField(default=None),
        ),
    ]
